[package]
name = "reno"
version = "0.1.0"
edition = "2021"
authors = ["Xiaoyang Liu <siujoeng.lau@gmail.com>"]
description = "Implementation of the Open Container Initiative Runtime Specification"

[dependencies]
caps = "0.5.4"
clap = { version = "3.2.22", features = ["derive"] }
nix = "0.25.0"
oci-spec = "0.5.8"
procfs = "0.14.1"
serde = "1.0.145"
serde_json = "1.0.85"
